### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by Blu3FireEdeN** [RienBijl/Scoreboard-revision#1]
Hello, there is an error with "PlayerJoinEvent" in the console.
Spigot : 1.12.2
Plugins :  MinePacks, PlaytimePlus, PlaceholderAPI, CustomRecipes, CustomEnchants, VoxelSniper, Enchants, WorldEdit, ClearLag, WorldBorder, Multiverse-Core, ProtocolLib, LibsDisguises, iDisguise, iConomy, PlaytimeReward, PermissionsEx, CS-CoreLib, mcMMO, Multiverse-Portals, Vault, WorldEditSelectionVisualizer, Scoreboard-revision, Rankup, LWC, HolographicDisplays, WorldGuard, ChestCommands, Slimefun, Orebfuscator4, CustomEnderChest, AreaShop, Essentials, GadgetsMenu, MarriageMaster, Jobs, mcMMOAction, HeadDatabase, SilkSpawners, McMMOExtras, Citizens, AdvancedAchievements, EssentialsChat, TimeIsMoney, Lottery, HolographicExtension, ChestShop, Quests, EssentialsGeoIP, CommandNPC, EssentialsSpawn, WorldGuardExtraFlags, CompatNoCheatPlus, Towny, NoCheatPlus, TownyChat, Shopkeepers, DiscordSRV, MobArena, TownyNameUpdater, mcMMO-Towny

Thanks !

[08:31:47] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to Scoreboard-revision vR3 1.0 BETA
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.NoSuchMethodError: org.bukkit.scoreboard.Scoreboard.registerNewObjective(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Lorg/bukkit/scoreboard/Objective;
	at rien.bijl.Scoreboard.r.board.slimboard.Slimboard.<init>(Slimboard.java:33) ~[?:?]
	at rien.bijl.Scoreboard.r.board.ScoreboardHolder.<init>(ScoreboardHolder.java:28) ~[?:?]
	at rien.bijl.Scoreboard.r.board.events.EIntergrate.Intergrate(EIntergrate.java:25) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_72]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_72]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_72]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-fb414fe]
	... 14 more

**Comment by RienBijl** [comment]
Incompatible spigot version, please send the response from /version to me. Also include your configuration file. Also try disabling any plugin that uses sidebars/scoreboards, alters display/top-names or anything that uses the scoreboard library included with spigot

**Comment by RienBijl** [comment]
Fixed as of
https://github.com/RienBijl/Scoreboard-revision/commit/053607ec4e614fdbdefa6770cad8efdba45faf73
