### ISSUE TITLE
Error in console, plugin still functions fine.

### ISSUE THREAD

**Issue by Vehzx** [RienBijl/Scoreboard-revision#14]
Getting this error in console every now and then, although plugin seems to work fine still.

> [Scoreboard-revision] Plugin Scoreboard-revision vR3 1.4.2 RELEASE generated an exception while executing task 42
> java.util.ConcurrentModificationException: null
> at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_212]
> at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_212]
> at rien.bijl.Scoreboard.r.board.App.run(App.java:121) ~[?:?]
> at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-167]
> at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-167]
> at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-167]
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_212]
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_212]
> at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

**Comment by successed** [comment]
`[21:54:34] [Craft Scheduler Thread - 603/WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR3 1.4.2 RELEASE generated an exception while executing task 289
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_222]
	at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_222]
	at rien.bijl.Scoreboard.r.board.App.run(App.java:121) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-194]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-194]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-194]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

**Comment by grzegorzgogolewski** [comment]
This happens when someone logs in or out. It also happens to me.
