### ISSUE TITLE
console eror

### ISSUE THREAD

**Issue by successed** [RienBijl/Scoreboard-revision#22]
Console error

[11:18:23 WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR3 1.4.2 RELEASE generated an exception while executing task 47
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_232]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_232]
        at rien.bijl.Scoreboard.r.board.App.run(App.java:121) ~[?:?]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-237]
        at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.14.4.jar:git-Paper-237]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.14.4.jar:git-Paper-237]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_232]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_232]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

**Comment by successed** [comment]
we waiting 25 day...
