### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ahmed-Khaled2** [RienBijl/Scoreboard-revision#6]
I'm not sure why this happens, But when it does somethings everyone on my server gets kicked.

[16:36:54 WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR4 1.1 RELEASE generated an exception while executing task 40
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_282]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_282]
        at rien.bijl.Scoreboard.r.Board.ConfigBoard.run(ConfigBoard.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[16:36:54 WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR4 1.1 RELEASE generated an exception while executing task 40
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_282]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_282]
        at rien.bijl.Scoreboard.r.Board.ConfigBoard.run(ConfigBoard.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
[16:36:54 WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR4 1.1 RELEASE generated an exception while executing task 40
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_282]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_282]
        at rien.bijl.Scoreboard.r.Board.ConfigBoard.run(ConfigBoard.java:80) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.12.2.jar:git-Spigot-dcd1643-e60fc34]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]

**Comment by RienBijl** [comment]
Please add a list of plugins and what spigot version/fork you run
