### ISSUE TITLE
[BUG] Error

### ISSUE THREAD

**Issue by alkolodziej** [RienBijl/Scoreboard-revision#8]
When sb left server:
`[11:38:54] [Craft Scheduler Thread - 11 - Scoreboard-revision/WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR4 1.1 RELEASE generated an exception while executing task 16
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
	at rien.bijl.Scoreboard.r.Board.ConfigBoard.run(ConfigBoard.java:80) ~[?:?]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1024]
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1024]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1024]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
`

Purpur 1.16.5,
![image](https://user-images.githubusercontent.com/60829268/113405866-ce4fed00-93aa-11eb-8e48-13c50d28fead.png)

**Comment by iMarianARG** [comment]
idk, i too have purpur 1.16.5

**Comment by ItsNyoty** [comment]
Same problem but then with Tuinity 

```[21:30:40 WARN]: [Scoreboard-revision] Plugin Scoreboard-revision vR4 1.1 RELEASE generated an exception while executing task 35
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
        at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
        at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
        at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
        at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
        at rien.bijl.Scoreboard.r.Board.Animations.Row.update(Row.java:57) ~[?:?]
        at rien.bijl.Scoreboard.r.Board.ConfigBoard.run(ConfigBoard.java:77) ~[?:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[patched_1.17.1.jar:git-Tuinity-"dc9d19c"]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[patched_1.17.1.jar:git-Tuinity-"dc9d19c"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.17.1.jar:git-Tuinity-"dc9d19c"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]```
