### ISSUE TITLE
Error when player leave the server

### ISSUE THREAD

**Issue by plagoutte** [RienBijl/Scoreboard-revision#9]
Hello, 

I get this error when a player disconnect :  

```
[22:53:13 INFO]: pierre_the_geek lost connection: Disconnected
[22:53:13 ERROR]: Could not pass event PlayerQuitEvent to Scoreboard-revision vR3 1.3.1 RELEASE
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:403) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1335) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:326) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:143) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: Not scheduled yet
        at org.bukkit.scheduler.BukkitRunnable.checkScheduled(BukkitRunnable.java:156) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.scheduler.BukkitRunnable.isCancelled(BukkitRunnable.java:20) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at rien.bijl.Scoreboard.r.board.events.EDeintergrate.Deintergrate(EDeintergrate.java:26) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor629.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        ... 12 more
[22:53:13 ERROR]: Could not pass event PlayerQuitEvent to Scoreboard-revision vR3 1.3.1 RELEASE
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:66) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:507) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:492) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.PlayerList.disconnect(PlayerList.java:403) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1335) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.NetworkManager.handleDisconnection(NetworkManager.java:326) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:143) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:994) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalStateException: Not scheduled yet
        at org.bukkit.scheduler.BukkitRunnable.checkScheduled(BukkitRunnable.java:156) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at org.bukkit.scheduler.BukkitRunnable.isCancelled(BukkitRunnable.java:20) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        at rien.bijl.Scoreboard.r.board.events.EDeintergrate.Deintergrate(EDeintergrate.java:26) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor629.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:312) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
        ... 12 more
```

And I have a similar error when a player join the server.

Server info : 
```
>ver
[22:54:50 INFO]: This server is running CraftBukkit version git-Spigot-f09662d-7c395d4 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
[22:54:50 INFO]: You are 166 version(s) behind
>
```

**Comment by RienBijl** [comment]
https://github.com/RienBijl/Scoreboard-revision/projects/1

Exception boarded and will look into

**Comment by RienBijl** [comment]
Should be resolved.
